name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Npm_security_Test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Npm_security_test
      run: npm run npm-security-test

  Build_and_Unit_Test:
    runs-on: ubuntu-latest

    needs: Npm_security_Test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Unit Test
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo '@dimitar1985'


  Deploy_to_Render:
    runs-on: ubuntu-latest

    needs: Build_and_Unit_Test
    steps:
      - name: Deploy to production
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}